export default {
  SPLASH_SCREEN: 'SplashScreen',
  LOGIN_SCREEN: 'LoginScreen',
  SIGN_UP_SCREEN: 'SignUpScreen',
  EDIT_PROFILE_SCREEN: 'EditProfileScreen',
  CHANGE_PASSWORD_SCREEN: 'ChangePasswordScreen',
  FORGOT_PASSWORD_SCREEN: 'ForgotPasswordScreen',
  RESET_PASSWORD_SCREEN: 'ResetPasswordScreen',
  HOME_SCREEN: 'HomeScreen',
  SEARCH_SCREEN: 'SearchScreen',
  PROFILE_SCREEN: 'ProfileScreen',
  PRODUCT_DETAILS_SCREEN: 'ProductDetailsScreen',
  CART_SCREEN: 'CartScreen',
  CONFIRM_ORDER_SCREEN: 'ConfirmOrderScreen',
  PAYMENT_METHOD_SCREEN: 'PaymentMethodScreen',
  APP_NAVIGATION: 'AppNavigation',
  AUTH_NAVIGATION: 'AuthNavigation',
  ROOT: 'Root',
  ADMIN_ORDERS_SCREEN: 'AdminOrdersScreen',
  ADMIN_PANEL_SCREEN: 'AdminPanelScreen',
  CATEGORIES_SCREEN: 'CategoriesScreen',
  NEW_PRODUCT_SCREEN: 'NewProductScreen',
  PRODUCT_IMAGES_SCREEN: 'ProductImagesScreen',
  UPDATE_PRODUCT_SCREEN: 'UpdateProductScreen',
  APP_NAVIGATION: 'AppNavigation',
  HOME_STACK: 'HomeStack',
};
